package com.ecfghjp.aggregator.logs.adapter.service.enteties;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;


//I would test the POJOs as well unless they are generated by Lombok 
//to test if there is any logic written, which shouldnt be, in getters and setters
class LogAggregateRequestTest {

	@Test
	void testGetInputFilePaths() {
		fail("Not yet implemented");
	}

	@Test
	void testGetOutputFilePath() {
		fail("Not yet implemented");
	}

}
